# Generated by Django 3.1.4 on 2021-07-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.PositiveIntegerField(default='0000'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='identity',
            field=models.IntegerField(),
        ),
    ]
